# Generated by Django 3.1.7 on 2022-01-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('speaker', models.CharField(max_length=30)),
                ('record', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
    ]
