# Generated by Django 3.1.7 on 2022-01-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_podcast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
