# Generated by Django 3.1.7 on 2022-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcast_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='podcast/images'),
        ),
    ]
