# Generated by Django 3.1.7 on 2022-01-08 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='record',
            field=models.FileField(default=django.utils.timezone.now, upload_to='podcast/audio'),
            preserve_default=False,
        ),
    ]
